### ISSUE TITLE
Fix typo and grammatical incorrect 

### ISSUE THREAD

**Issue by elukuro** [elukuro/goheru-markdown-blog-react#3]
Fix typo or grammatical for article that you find in /src/article directory 

- [x] Tips 01 Use No Var Anymore @not-shoyo  ✅
- [x] Tips 02 How To Switch Value @not-shoyo  ✅
- [x] Tips 03 Unique Array @not-shoyo  ✅
- [x] Tips 04 How To Shorten If Else Statment @not-shoyo  ✅
- [x] Tips 05 No Undefined Value Pass In Your Functions Anymore @not-shoyo  ✅
- [x] Tips 06 Some Git Command That Might You Dont Know @not-shoyo  ✅
- [x] Tips 07 How To Duplicate Array @not-shoyo  ✅
- [x] Tips 08 Don't Use Float @not-shoyo  ✅
- [x] Tips 09 React State Hook Easy Way Copy @not-shoyo  ✅
- [x] Tips 10 React Effect Hook Easy Way @not-shoyo  ✅
- [x] Tips 11 Functional Or Class Component @not-shoyo  ✅
- [x] Tips 12 How To Clone Object Except One Or Some Keys @not-shoyo  ✅
- [x] Tips 13 Don't Do This A Guide Not To Curse By Other Developer @not-shoyo  ✅
- [x] Tips 14 Optional Chaining Copy @not-shoyo  ✅
- [x] Tips 15 Conditionally Calling Function @not-shoyo  ✅
- [x] Tips 16 Converting Number Without ParseInt @not-shoyo  ✅
- [x] Tips 17 Clean Code Tips 1 Variable @not-shoyo  ✅
- [x] Tips 18 Clean Code Tips 2 Function @not-shoyo  ✅
- [x] Tips 19 Clean Code Tips 3 Conditional @not-shoyo  ✅
- [x] Tips 20 Wierd Javascript @not-shoyo  ✅

If you want to contribute, please write a comment with title from this list so I can assign it to you

**Comment by not-shoyo** [comment]
> Fix typo or grammatical for article that you find in /src/article directory

I would like to claim this issue, or at the very least submit a sample and go forward from there.

**Comment by elukuro** [comment]
Yes you could, I will accept your pull request at least tomorrow so your contribution for hactoberfest will be count

**Comment by aishwaryeay** [comment]
can i contribute on it too?

**Comment by elukuro** [comment]
you're welcome to contribute, but make sure that you aren't fixing the same articles that already taken by @not-shoyo

**Comment by HiruniPerera** [comment]
Hi, Can I contribute to this?

**Comment by not-shoyo** [comment]
> can i contribute on it too?

If you are contributing, can you list the files you will be working on so that I can pick others?

**Comment by elukuro** [comment]
@HiruniPerera  if you want to contributing please comment with one of title from the list so I can assign it to you

**Comment by elukuro** [comment]
@not-shoyo  you could continue your work, please comment at which title you've working

**Comment by not-shoyo** [comment]
I am going to work on 07 and 08 next.

**Comment by not-shoyo** [comment]
@elukuro will you be fixing the merge conflicts?

**Comment by not-shoyo** [comment]
@elukuro i have pulled changes for 5 other files too now.

**Comment by elukuro** [comment]
I really appreciate your contribution @not-shoyo

**Comment by elukuro** [comment]
thank you @not-shoyo
